version: '1.0'

services:
  postgress:
    image: postgres:14
    container_name: hedgie
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: academy 
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: postgresql://username:pw@localhost:5432/academy
    depends_on:
      - postgres

volumes:
  postgres_data: